# Generated by Django 6.1 on 2026-09-04 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('server', 'Сервер'), ('switch', 'Коммутатор'), ('router', 'Маршрутизатор'), ('storage_system', 'СХД'), ('firewall', 'МСЭ'), ('crypto_gate', 'Крипто-шлюз')], db_index=True, max_length=20, verbose_name='Тип устройства')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('production_year', models.PositiveSmallIntegerField(blank=True, help_text='Год производства модели', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Год производства')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='commons.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель устройства',
                'verbose_name_plural': 'Модели устройств',
                'ordering': ['kind', 'vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, help_text='Уникален в рамках модели устройства', max_length=100, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, help_text='Глобально уникален', max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('purchase_year', models.PositiveSmallIntegerField(blank=True, help_text='Год приобретения устройства', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Год приобретения')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('management_protocols', models.ManyToManyField(blank=True, related_name='devices', to='commons.protocol', verbose_name='Протоколы управления')),
                ('operating_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='commons.operatingsystem', verbose_name='Операционная система')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.devicemodel', verbose_name='Модель устройства')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='NetworkPortGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_type', models.CharField(choices=[('rj45_fe', 'RJ-45 (Fast Ethernet 10/100 Mbps)'), ('rj45_ge', 'RJ-45 (Gigabit Ethernet 1 Gbps)'), ('rj45_10g', 'RJ-45 (10GBASE-T)'), ('gg45', 'GG45/ARJ45 (Категория 7/7A)'), ('tera', 'TERA (Категория 7/7A)'), ('sfp', 'SFP (100M/1G)'), ('sfp_plus', 'SFP+ (10G)'), ('sfp28', 'SFP28 (25G)'), ('qsfp_plus', 'QSFP+ (40G)'), ('qsfp28', 'QSFP28 (100G)'), ('xfp', 'XFP (10G)'), ('console', 'Console (RJ45/USB-B/Mini-USB)')], db_index=True, default='rj45_ge', max_length=20, verbose_name='Физический тип портов')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_groups', to='devices.devicemodel', verbose_name='Модель устройства')),
            ],
            options={
                'verbose_name': 'Группа портов',
                'verbose_name_plural': 'Группы сетевых портов',
                'ordering': ['device_model', 'physical_type'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalNetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя порта')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('disabled', 'Отключен (Admin Down)'), ('reserved', 'Зарезервирован'), ('faulty', 'Неисправен')], db_index=True, default='inactive', max_length=20, verbose_name='Статус порта')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_ports', to='devices.device', verbose_name='Устройство')),
                ('network_port_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_ports', to='devices.networkportgroup', verbose_name='Модель порта')),
            ],
            options={
                'verbose_name': 'Физический сетевой порт',
                'verbose_name_plural': 'Физические сетевые порты',
                'ordering': ['device', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['part_number'], name='device_model_part_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'part_number'), name='device_model_vendor_part_number_unique'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='device_serial_number_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['management_ip'], name='device_management_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['purchase_year'], name='device_purchase_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', None), _negated=True), models.Q(('serial_number', ''), _negated=True)), fields=('device_model', 'serial_number'), name='device_serial_number_unique_per_model'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('inventory_number', None), _negated=True), models.Q(('inventory_number', ''), _negated=True)), fields=('inventory_number',), name='device_inventory_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='networkportgroup',
            constraint=models.UniqueConstraint(fields=('device_model', 'physical_type'), name='network_port_group_device_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='physicalnetworkport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='physical_port_device_name_unique'),
        ),
    ]
