# Generated by Django 6.1 on 2026-08-15 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('base_clock_mhz', models.PositiveIntegerField(help_text='МГц', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Базовая частота')),
                ('cores', models.PositiveIntegerField(help_text='Количество ядер', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ядра')),
                ('threads', models.PositiveIntegerField(help_text='Количество потоков', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потоки')),
            ],
            options={
                'verbose_name': 'Модель CPU',
                'verbose_name_plural': 'Модели CPU',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, help_text='Уникален в рамках модели устройства', max_length=100, null=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, help_text='Глобально уникален', max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('purchase_year', models.PositiveSmallIntegerField(blank=True, help_text='Год приобретения устройства', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Год приобретения')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('server', 'Сервер'), ('switch', 'Коммутатор'), ('router', 'Маршрутизатор'), ('storage_system', 'СХД'), ('firewall', 'МСЭ'), ('crypto_gate', 'Крипто-шлюз')], db_index=True, max_length=20, verbose_name='Тип устройства')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('production_year', models.PositiveSmallIntegerField(blank=True, help_text='Год производства модели', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Год производства')),
            ],
            options={
                'verbose_name': 'Модель устройства',
                'verbose_name_plural': 'Модели устройств',
                'ordering': ['kind', 'vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='DiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('disk_type', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD'), ('nvme', 'NVMe'), ('ssd_nvme', 'SSD/NVMe'), ('ssd_hdd', 'SSD/HDD'), ('hdd_ssd', 'HDD/SSD'), ('hdd_nvme', 'HDD/NVMe'), ('nvme_ssd', 'NVMe/SSD')], db_index=True, max_length=20, verbose_name='Тип диска')),
                ('size_gb', models.PositiveIntegerField(help_text='ГБ', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Объем')),
                ('rpm', models.PositiveIntegerField(blank=True, help_text='об/мин; для SSD/NVME обычно не заполняется', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Скорость вращения')),
            ],
            options={
                'verbose_name': 'Модель диска',
                'verbose_name_plural': 'Модели дисков',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='MotherboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('socket_type', models.CharField(choices=[('am4', 'AM4'), ('am5', 'AM5'), ('amd', 'AMD'), ('intel', 'Intel')], max_length=20, verbose_name='Сокет')),
                ('chipset', models.CharField(blank=True, max_length=50, verbose_name='Чипсет')),
                ('max_memory_gb', models.PositiveIntegerField(help_text='ГБ', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный объем памяти')),
                ('max_memory_type', models.CharField(blank=True, choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=20, verbose_name='Тип максимальной памяти')),
            ],
            options={
                'verbose_name': 'Модель материнской платы',
                'verbose_name_plural': 'Модели материнских плат',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='RAMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('memory_type', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=20, verbose_name='Тип памяти')),
                ('memory_size_gb', models.PositiveIntegerField(help_text='ГБ', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Объем памяти')),
                ('base_frequency_mhz', models.PositiveIntegerField(help_text='МГц', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Базовая частота')),
            ],
            options={
                'verbose_name': 'Модель RAM',
                'verbose_name_plural': 'Модели RAM',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('cpu_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='devices.cpumodel', verbose_name='Модель CPU')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.devicemodel', verbose_name='Модель устройства'),
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
                ('disk_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='devices.diskmodel', verbose_name='Модель диска')),
            ],
            options={
                'verbose_name': 'Диск',
                'verbose_name_plural': 'Диски',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
                ('motherboard_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboards', to='devices.motherboardmodel', verbose_name='Модель материнской платы')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.CreateModel(
            name='NetworkPortGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_type', models.CharField(choices=[('rj45_fe', 'RJ-45 (Fast Ethernet 10/100 Mbps)'), ('rj45_ge', 'RJ-45 (Gigabit Ethernet 1 Gbps)'), ('rj45_10g', 'RJ-45 (10GBASE-T)'), ('gg45', 'GG45/ARJ45 (Категория 7/7A)'), ('tera', 'TERA (Категория 7/7A)'), ('sfp', 'SFP (100M/1G)'), ('sfp_plus', 'SFP+ (10G)'), ('sfp28', 'SFP28 (25G)'), ('qsfp_plus', 'QSFP+ (40G)'), ('qsfp28', 'QSFP28 (100G)'), ('xfp', 'XFP (10G)'), ('console', 'Console (RJ45/USB-B/Mini-USB)')], db_index=True, default='rj45_ge', max_length=20, verbose_name='Физический тип портов')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_groups', to='devices.devicemodel', verbose_name='Модель устройства')),
            ],
            options={
                'verbose_name': 'Группа портов',
                'verbose_name_plural': 'Группы сетевых портов',
                'ordering': ['device_model', 'physical_type'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='operating_system_name_unique')],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.operatingsystem', verbose_name='Операционная система'),
        ),
        migrations.CreateModel(
            name='PhysicalNetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя порта')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('disabled', 'Отключен (Admin Down)'), ('reserved', 'Зарезервирован'), ('faulty', 'Неисправен')], db_index=True, default='inactive', max_length=20, verbose_name='Статус порта')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_ports', to='devices.device', verbose_name='Устройство')),
                ('network_port_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_ports', to='devices.networkportgroup', verbose_name='Модель порта')),
            ],
            options={
                'verbose_name': 'Физический сетевой порт',
                'verbose_name_plural': 'Физические сетевые порты',
                'ordering': ['device', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='protocol_name_unique')],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='management_protocols',
            field=models.ManyToManyField(blank=True, related_name='devices', to='devices.protocol', verbose_name='Протоколы управления'),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
                ('ram_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rams', to='devices.rammodel', verbose_name='Модель RAM')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='vendor_name_unique')],
            },
        ),
        migrations.AddField(
            model_name='rammodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='diskmodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='devices.vendor', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель'),
        ),
        migrations.AddConstraint(
            model_name='networkportgroup',
            constraint=models.UniqueConstraint(fields=('device_model', 'physical_type'), name='network_port_group_device_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='physicalnetworkport',
            constraint=models.UniqueConstraint(fields=('device', 'network_port_model'), name='physical_port_device_port_unique'),
        ),
        migrations.AddConstraint(
            model_name='physicalnetworkport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='physical_port_device_name_unique'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='device_serial_number_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['management_ip'], name='device_management_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['purchase_year'], name='device_purchase_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', None), _negated=True), models.Q(('serial_number', ''), _negated=True)), fields=('device_model', 'serial_number'), name='device_serial_number_unique_per_model'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('inventory_number', None), _negated=True), models.Q(('inventory_number', ''), _negated=True)), fields=('inventory_number',), name='device_inventory_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='rammodel',
            constraint=models.CheckConstraint(condition=models.Q(('memory_size_gb__gte', 1), ('base_frequency_mhz__gte', 1)), name='ram_model_size_frequency_positive'),
        ),
        migrations.AddConstraint(
            model_name='motherboardmodel',
            constraint=models.CheckConstraint(condition=models.Q(('max_memory_gb__gte', 1)), name='motherboard_model_max_memory_positive'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('size_gb__gte', 1)), name='disk_model_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('rpm', None), ('rpm__gte', 1), _connector='OR'), name='disk_model_rpm_null_or_gte_1'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['part_number'], name='device_model_part_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'part_number'), name='device_model_vendor_part_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='cpumodel',
            constraint=models.CheckConstraint(condition=models.Q(('cores__gte', 1), ('threads__gte', 1)), name='cpu_model_cores_threads_positive'),
        ),
        migrations.AddConstraint(
            model_name='cpumodel',
            constraint=models.CheckConstraint(condition=models.Q(('threads__gte', models.F('cores'))), name='cpu_model_threads_gte_cores'),
        ),
    ]
