# Generated by Django 6.1 on 2026-08-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='device',
        ),
        migrations.RemoveConstraint(
            model_name='cpumodel',
            name='cpu_model_cores_threads_positive',
        ),
        migrations.RemoveConstraint(
            model_name='cpumodel',
            name='cpu_model_threads_gte_cores',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='device',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='disk_model',
        ),
        migrations.RemoveConstraint(
            model_name='diskmodel',
            name='disk_model_size_positive',
        ),
        migrations.RemoveConstraint(
            model_name='diskmodel',
            name='disk_model_rpm_null_or_gte_1',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='device',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='motherboard_model',
        ),
        migrations.RemoveConstraint(
            model_name='motherboardmodel',
            name='motherboard_model_max_memory_positive',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='device',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='ram_model',
        ),
        migrations.RemoveConstraint(
            model_name='rammodel',
            name='ram_model_size_frequency_positive',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.RemoveField(
            model_name='cpumodel',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.RemoveField(
            model_name='diskmodel',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.RemoveField(
            model_name='motherboardmodel',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.RemoveField(
            model_name='rammodel',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='CPUModel',
        ),
        migrations.DeleteModel(
            name='DiskModel',
        ),
        migrations.DeleteModel(
            name='MotherboardModel',
        ),
        migrations.DeleteModel(
            name='RAMModel',
        ),
    ]
