# Generated by Django 6.1 on 2026-09-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Название модели по спецификации вендора', max_length=100, verbose_name='Модель')),
                ('capacity_gb', models.PositiveIntegerField(verbose_name='Емкость (ГБ)')),
                ('media_type', models.CharField(choices=[('HDD', 'Hard Disk Drive (Магнитный)'), ('SSD', 'Solid State Drive (SATA/SAS SSD)'), ('NVME', 'NVMe SSD (Высокоскоростной)')], max_length=10, verbose_name='Тип носителя')),
                ('interface', models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('PCIE', 'PCIe (NVMe)')], max_length=10, verbose_name='Интерфейс')),
                ('form_factor', models.CharField(choices=[('3.5_LFF', '3.5" LFF'), ('2.5_SFF', '2.5" SFF'), ('M.2', 'M.2'), ('U.2_U3', 'U.2 / U.3'), ('EDSFF', 'EDSFF')], max_length=15, verbose_name='Форм-фактор')),
                ('device_class', models.CharField(choices=[('ENTERPRISE', 'Серверный / Enterprise'), ('CONSUMER', 'Потребительский'), ('NAS', 'NAS'), ('SURVEILLANCE', 'Для видеонаблюдения'), ('UNKNOWN', 'Не определен')], default='UNKNOWN', help_text='Серверный / потребительский класс устройства', max_length=20, verbose_name='Класс диска')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель диска',
                'verbose_name_plural': 'Модели дисков',
                'ordering': ['vendor', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, help_text='Внутренний номер учета организации', max_length=64, null=True, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('ACTIVE', 'В эксплуатации'), ('SPARE', 'В резерве (ЗИП)'), ('FAULTY', 'Неисправен'), ('RETIRED', 'Списан')], default='SPARE', max_length=16, verbose_name='Статус')),
                ('firmware', models.CharField(blank=True, max_length=64, verbose_name='Версия прошивки')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disks', to='devices.device', verbose_name='Устройство')),
                ('disk_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_disks', to='devices.diskmodel', verbose_name='Модель диска')),
            ],
            options={
                'verbose_name': 'Физический диск',
                'verbose_name_plural': 'Физические диски',
                'ordering': ['disk_model__vendor', 'disk_model__model_name', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='diskmodel',
            index=models.Index(fields=['device_class'], name='devices_dis_device__b531d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'model_name'), name='uniq_vendor_model_name'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'NVME'), _negated=True), ('interface', 'PCIE'), _connector='OR'), name='diskmodel_nvme_must_use_pcie'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'NVME'), _negated=True), ('form_factor__in', ['U.2_U3', 'M.2', 'EDSFF']), _connector='OR'), name='diskmodel_nvme_valid_form_factors'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'HDD'), _negated=True), ('interface__in', ['SATA', 'SAS']), _connector='OR'), name='diskmodel_hdd_must_use_sata_sas'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'HDD'), _negated=True), ('form_factor__in', ['3.5_LFF', '2.5_SFF']), _connector='OR'), name='diskmodel_hdd_valid_form_factors'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'SSD'), _negated=True), ('interface__in', ['SATA', 'SAS']), _connector='OR'), name='diskmodel_ssd_must_use_sata_sas'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'SSD'), _negated=True), ('form_factor__in', ['2.5_SFF', 'M.2', 'U.2_U3', 'EDSFF']), _connector='OR'), name='diskmodel_ssd_valid_form_factors'),
        ),
        migrations.AddIndex(
            model_name='disk',
            index=models.Index(fields=['status', 'disk_model'], name='devices_dis_status_8b552b_idx'),
        ),
        migrations.AddIndex(
            model_name='disk',
            index=models.Index(fields=['serial_number'], name='devices_dis_serial__539610_idx'),
        ),
        migrations.AddConstraint(
            model_name='disk',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_number__isnull', True), _negated=True), fields=('inventory_number',), name='uniq_inventory_number'),
        ),
    ]
