# Generated by Django 6.1 on 2026-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_cpu_cpu_model_remove_cpu_device_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='physicalnetworkport',
            name='physical_port_device_port_unique',
        ),
        migrations.RenameField(
            model_name='physicalnetworkport',
            old_name='network_port_model',
            new_name='network_port_group',
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, default='', help_text='Уникален в рамках модели устройства', max_length=100, verbose_name='Серийный номер'),
            preserve_default=False,
        ),
    ]
