# Generated by Django 6.1 on 2026-09-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_diskmodel_disk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskmodel',
            name='interface',
            field=models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('PCIE', 'NVMe')], max_length=10, verbose_name='Интерфейс'),
        ),
        migrations.AlterField(
            model_name='diskmodel',
            name='media_type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD (SATA/SAS)'), ('NVME', 'SSD (NVMe)')], max_length=10, verbose_name='Тип носителя'),
        ),
    ]
