# Generated by Django 6.1 on 2026-08-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_physicalnetworkport_physical_port_device_port_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='production',
            field=models.CharField(choices=[('foreign', 'За рубежом'), ('domestic', 'Отечественный')], default='foreign', max_length=100),
            preserve_default=False,
        ),
    ]
