# Generated by Django 6.1 on 2026-09-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_diskmodel_interface_alter_diskmodel_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='firmware',
        ),
    ]
