# Generated by Django 6.1 on 2026-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_disk_firmware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='kind',
            field=models.CharField(choices=[('server', 'Серверы'), ('switch', 'Коммутаторы'), ('router', 'Маршрутизаторы'), ('storage_system', 'СХД'), ('firewall', 'МСЭ'), ('crypto_gate', 'Крипто-шлюзы')], db_index=True, max_length=20, verbose_name='Тип устройства'),
        ),
    ]
