# Generated by Django 6.1 on 2026-08-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_vendor_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, choices=[('Великобритания', 'Великобритания'), ('Германия', 'Германия'), ('Дания', 'Дания'), ('Израиль', 'Израиль'), ('Ирландия', 'Ирландия'), ('Италия', 'Италия'), ('Канада', 'Канада'), ('Китай', 'Китай'), ('Латвия', 'Латвия'), ('Россия', 'Россия'), ('США', 'США'), ('Тайвань', 'Тайвань'), ('Финляндия', 'Финляндия'), ('Швейцария', 'Швейцария'), ('Швеция', 'Швеция'), ('Южная Корея', 'Южная Корея'), ('Япония', 'Япония')], max_length=100, null=True),
        ),
    ]
