# Generated by Django 6.1 on 2026-09-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicemodel_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('on', 'Включен'), ('off', 'Выключен'), ('broken', 'Не исправен'), ('unreachable', 'Не доступен'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='Статус'),
        ),
    ]
