# Generated by Django 6.1 on 2026-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_vendor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, choices=[('GB', 'Великобритания'), ('DE', 'Германия'), ('DK', 'Дания'), ('IL', 'Израиль'), ('IE', 'Ирландия'), ('IT', 'Италия'), ('CA', 'Канада'), ('CN', 'Китай'), ('LV', 'Латвия'), ('RU', 'Россия'), ('US', 'США'), ('TW', 'Тайвань'), ('FI', 'Финляндия'), ('CH', 'Швейцария'), ('SE', 'Швеция'), ('KR', 'Южная Корея'), ('JP', 'Япония')], max_length=100, null=True),
        ),
    ]
