# Generated by Django 6.1 on 2026-08-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_operating_system_alter_vendor_country'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operatingsystem',
            name='operating_system_name_unique',
        ),
        migrations.RemoveField(
            model_name='device',
            name='operating_system',
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
    ]
