# Generated by Django 6.1 on 2026-09-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_socket'),
        ('devices', '0006_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Полное наименование (например, Xeon Gold 6438Y+ или Ryzen 9 7950X)', max_length=100, verbose_name='Модель')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='Part Number (P/N)')),
                ('cores', models.PositiveIntegerField(verbose_name='Ядра')),
                ('threads', models.PositiveIntegerField(verbose_name='Потоки')),
                ('base_frequency_mhz', models.PositiveIntegerField(verbose_name='Базовая частота (МГц)')),
                ('max_frequency_mhz', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. частота Turbo (МГц)')),
                ('l3_cache_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кэш L3 (МБ)')),
                ('memory_type', models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('LPDDR4', 'LPDDR4/4X'), ('LPDDR5', 'LPDDR5/5X'), ('OTHER', 'Другой')], max_length=10, verbose_name='Тип памяти')),
                ('memory_speed_mts', models.PositiveIntegerField(blank=True, help_text='Например: 4800, 5600, 3200', null=True, verbose_name='Скорость памяти (MT/s)')),
                ('segment', models.CharField(blank=True, choices=[('SERVER', 'Серверный'), ('DESKTOP', 'Настольный'), ('WORKSTATION', 'Рабочая станция'), ('EMBEDDED', 'Встраиваемый')], db_index=True, help_text='К какой категории относится процессор', max_length=20, verbose_name='Сегмент')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processor_models', to='commons.socket', verbose_name='Сокет')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель процессора',
                'verbose_name_plural': 'Модели процессоров',
                'ordering': ['vendor', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, help_text='FPO / S/N на крышке процессора', max_length=100, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('ACTIVE', 'В эксплуатации'), ('SPARE', 'В резерве (ЗИП)'), ('FAULTY', 'Неисправен'), ('RETIRED', 'Списан')], default='SPARE', max_length=16, verbose_name='Статус')),
                ('stepping', models.CharField(blank=True, help_text='Ревизия кристалла (например: M1, B1)', max_length=20, verbose_name='Степпинг / ревизия')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processors', to='devices.device', verbose_name='Устройство')),
                ('processor_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_processors', to='devices.processormodel', verbose_name='Модель процессора')),
            ],
            options={
                'verbose_name': 'Физический процессор',
                'verbose_name_plural': 'Физические процессоры',
                'ordering': ['processor_model__vendor', 'processor_model__model_name', 'serial_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='processormodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'model_name'), name='uniq_proc_vendor_model'),
        ),
        migrations.AddConstraint(
            model_name='processormodel',
            constraint=models.UniqueConstraint(condition=models.Q(('part_number', ''), _negated=True), fields=('part_number',), name='uniq_proc_part_number'),
        ),
        migrations.AddConstraint(
            model_name='processormodel',
            constraint=models.CheckConstraint(condition=models.Q(('threads__gte', models.F('cores'))), name='proc_threads_gte_cores'),
        ),
        migrations.AddConstraint(
            model_name='processormodel',
            constraint=models.CheckConstraint(condition=models.Q(('max_frequency_mhz__isnull', True), ('max_frequency_mhz__gte', models.F('base_frequency_mhz')), _connector='OR'), name='proc_turbo_gte_base'),
        ),
        migrations.AddConstraint(
            model_name='processormodel',
            constraint=models.CheckConstraint(condition=models.Q(('cores__gt', 0)), name='proc_cores_positive'),
        ),
        migrations.AddConstraint(
            model_name='processormodel',
            constraint=models.CheckConstraint(condition=models.Q(('base_frequency_mhz__gt', 0)), name='proc_base_freq_positive'),
        ),
        migrations.AddIndex(
            model_name='processor',
            index=models.Index(fields=['status', 'processor_model'], name='devices_pro_status_e21fef_idx'),
        ),
        migrations.AddIndex(
            model_name='processor',
            index=models.Index(fields=['serial_number'], name='devices_pro_serial__f45225_idx'),
        ),
        migrations.AddConstraint(
            model_name='processor',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_number__isnull', True), _negated=True), fields=('inventory_number',), name='uniq_proc_inventory_number'),
        ),
    ]
