# Generated by Django 6.1 on 2026-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_processormodel_processor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processormodel',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
    ]
