# Generated by Django 6.1 on 2026-08-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_operatingsystem_operating_system_name_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('family', models.CharField(choices=[('linux', 'Linux'), ('windows_desktop', 'Windows (клиентская)'), ('windows_server', 'Windows Server'), ('unix', 'UNIX'), ('bsd', 'BSD'), ('macos', 'macOS'), ('network_os', 'Сетевая ОС / прошивка'), ('hypervisor', 'Гипервизор'), ('storage_os', 'ОС СХД'), ('security_os', 'ОС безопасности (МСЭ, криптошлюз)'), ('embedded', 'Встроенная / специализированная'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Семейство ОС')),
                ('codename', models.CharField(blank=True, help_text='Например: Jammy Jellyfish, 22H2, VRP V200R019.', max_length=80, verbose_name='Кодовое наименование')),
                ('version', models.CharField(blank=True, help_text='Например: 22.04, 2022, 17.9.4, ESXi 8.0.', max_length=64, verbose_name='Версия')),
                ('edition', models.CharField(blank=True, help_text='Например: Standard, Datacenter, Enterprise, Community Edition.', max_length=100, verbose_name='Редакция / вариант')),
                ('build', models.CharField(blank=True, help_text='Номер сборки, прошивки или ревизии, если применимо.', max_length=80, verbose_name='Сборка / прошивка')),
                ('architecture', models.CharField(blank=True, choices=[('x86', 'x86 (32-bit)'), ('x86_64', 'x86-64'), ('arm32', 'ARM (32-bit)'), ('arm64', 'ARM64 (AArch64)'), ('ppc64le', 'POWER (ppc64le)'), ('s390x', 'IBM Z (s390x)'), ('mips', 'MIPS'), ('riscv', 'RISC-V'), ('unknown', 'Неизвестна')], help_text='Архитектура процессора, если применимо.', max_length=20, verbose_name='Архитектура')),
                ('kernel', models.CharField(blank=True, help_text='Версия ядра или базовой платформы, если нужно детализировать.', max_length=80, verbose_name='Ядро')),
                ('is_lts', models.BooleanField(default=False, help_text='Признак версии с длительной поддержкой.', verbose_name='LTS')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('eol_date', models.DateField(blank=True, help_text='EOL / End of Life / End of Support, если известно.', null=True, verbose_name='Дата окончания поддержки')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_systems', to='devices.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
                'db_table': 'devices_operating_system',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.operatingsystem', verbose_name='Операционная система'),
        ),
        migrations.AddIndex(
            model_name='operatingsystem',
            index=models.Index(fields=['family'], name='devices_os_family_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingsystem',
            index=models.Index(fields=['eol_date'], name='devices_os_eol_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='operatingsystem',
            constraint=models.UniqueConstraint(fields=('vendor', 'name', 'version', 'edition', 'build'), name='uniq_devices_operating_system'),
        ),
        migrations.AddConstraint(
            model_name='operatingsystem',
            constraint=models.CheckConstraint(condition=models.Q(('release_date__isnull', True), ('eol_date__isnull', True), ('eol_date__gte', models.F('release_date')), _connector='OR'), name='devices_os_eol_not_before_release'),
        ),
    ]
