# Generated by Django 6.1 on 2026-09-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_processormodel_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(help_text='Samsung, Micron, SK Hynix, Kingston и т.д.', max_length=100, verbose_name='Производитель')),
                ('model_name', models.CharField(help_text='Например: M393A4K40DB3-CWE (Samsung DDR4-3200 RDIMM)', max_length=100, verbose_name='Модель')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='Part Number (P/N)')),
                ('memory_type', models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('LPDDR4', 'LPDDR4/4X'), ('LPDDR5', 'LPDDR5/5X'), ('OTHER', 'Другой')], max_length=10, verbose_name='Тип памяти')),
                ('memory_speed_mts', models.PositiveIntegerField(help_text='Например: 3200, 4800, 5600', verbose_name='Скорость (MT/s)')),
                ('capacity_gb', models.PositiveIntegerField(verbose_name='Объём (ГБ)')),
                ('form_factor', models.CharField(choices=[('DIMM', 'DIMM (288-pin, настольные/серверные)'), ('SO-DIMM', 'SO-DIMM (ноутбуки, компактные системы)'), ('RDIMM', 'RDIMM (Registered DIMM, серверные)'), ('LRDIMM', 'LRDIMM (Load-Reduced DIMM, серверные)'), ('MCRDIMM', 'MCRDIMM (Multiplexer Clocked, DDR5 серверные)')], max_length=15, verbose_name='Форм-фактор')),
                ('latency_cl', models.PositiveIntegerField(blank=True, help_text='CAS Latency, например: 22, 16, 40', null=True, verbose_name='Латентность (CL)')),
            ],
            options={
                'verbose_name': 'Модель памяти',
                'verbose_name_plural': 'Модели памяти',
                'ordering': ['vendor', 'model_name'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'model_name'), name='uniq_ram_vendor_model'), models.UniqueConstraint(condition=models.Q(('part_number', ''), _negated=True), fields=('part_number',), name='uniq_ram_part_number'), models.CheckConstraint(condition=models.Q(('memory_speed_mts__gt', 0)), name='ram_speed_positive'), models.CheckConstraint(condition=models.Q(('capacity_gb__gt', 0)), name='ram_capacity_positive')],
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='SPD серийный номер', max_length=100, unique=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('ACTIVE', 'В эксплуатации'), ('SPARE', 'В резерве (ЗИП)'), ('FAULTY', 'Неисправна'), ('RETIRED', 'Списана')], default='SPARE', max_length=16, verbose_name='Статус')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram_modules', to='devices.device', verbose_name='Устройство')),
                ('ram_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_ram_modules', to='devices.rammodel', verbose_name='Модель памяти')),
            ],
            options={
                'verbose_name': 'Физическая память',
                'verbose_name_plural': 'Физическая память',
                'ordering': ['ram_model__vendor', 'ram_model__model_name', 'serial_number'],
                'indexes': [models.Index(fields=['status', 'ram_model'], name='devices_ram_status_7b2c1e_idx'), models.Index(fields=['serial_number'], name='devices_ram_serial__35629b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('inventory_number__isnull', True), _negated=True), fields=('inventory_number',), name='uniq_ram_inventory_number')],
            },
        ),
    ]
