# Generated by Django 6.1 on 2026-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='operating_system_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='protocol_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('production', models.CharField(choices=[('foreign', 'За рубежом'), ('domestic', 'Отечественный')], max_length=100)),
                ('country', models.CharField(blank=True, choices=[('GB', 'Великобритания'), ('DE', 'Германия'), ('DK', 'Дания'), ('IL', 'Израиль'), ('IE', 'Ирландия'), ('IT', 'Италия'), ('CA', 'Канада'), ('CN', 'Китай'), ('LV', 'Латвия'), ('RU', 'Россия'), ('US', 'США'), ('TW', 'Тайвань'), ('FI', 'Финляндия'), ('CH', 'Швейцария'), ('SE', 'Швеция'), ('KR', 'Южная Корея'), ('JP', 'Япония')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='vendor_name_unique')],
            },
        ),
    ]
