# Generated by Django 6.1 on 2026-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: LGA1700, AM5, SP5', max_length=30, unique=True, verbose_name='Название сокета')),
                ('full_name', models.CharField(blank=True, help_text='Например: Intel LGA 1700, AMD Socket AM5', max_length=100, verbose_name='Полное название')),
                ('socket_type', models.CharField(blank=True, choices=[('PGA', 'PGA (Pin Grid Array)'), ('LGA', 'LGA (Land Grid Array)'), ('BGA', 'BGA (Ball Grid Array)'), ('OTHER', 'Другой')], max_length=10, verbose_name='Тип сокета')),
                ('vendor', models.CharField(blank=True, choices=[('INTEL', 'Intel'), ('AMD', 'AMD'), ('ARM', 'ARM'), ('OTHER', 'Другой')], max_length=20, verbose_name='Производитель')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сокет',
                'verbose_name_plural': 'Сокеты',
                'ordering': ['vendor', 'name'],
            },
        ),
    ]
