# Generated by Django 6.1 on 2026-08-16 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_remove_cpu_cpu_model_remove_cpu_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('base_clock_mhz', models.PositiveIntegerField(help_text='МГц', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Базовая частота')),
                ('cores', models.PositiveIntegerField(help_text='Количество ядер', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ядра')),
                ('threads', models.PositiveIntegerField(help_text='Количество потоков', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потоки')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель CPU',
                'verbose_name_plural': 'Модели CPU',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
                ('cpu_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='components.cpumodel', verbose_name='Модель CPU')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='DiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('disk_type', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD'), ('nvme', 'NVMe'), ('ssd_nvme', 'SSD/NVMe'), ('ssd_hdd', 'SSD/HDD'), ('hdd_ssd', 'HDD/SSD'), ('hdd_nvme', 'HDD/NVMe'), ('nvme_ssd', 'NVMe/SSD')], db_index=True, max_length=20, verbose_name='Тип диска')),
                ('size_gb', models.PositiveIntegerField(help_text='ГБ', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Объем')),
                ('rpm', models.PositiveIntegerField(blank=True, help_text='об/мин; для SSD/NVME обычно не заполняется', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Скорость вращения')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель диска',
                'verbose_name_plural': 'Модели дисков',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
                ('disk_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='components.diskmodel', verbose_name='Модель диска')),
            ],
            options={
                'verbose_name': 'Диск',
                'verbose_name_plural': 'Диски',
            },
        ),
        migrations.CreateModel(
            name='MotherboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('socket_type', models.CharField(choices=[('am4', 'AM4'), ('am5', 'AM5'), ('amd', 'AMD'), ('intel', 'Intel')], max_length=20, verbose_name='Сокет')),
                ('chipset', models.CharField(blank=True, max_length=50, verbose_name='Чипсет')),
                ('max_memory_gb', models.PositiveIntegerField(help_text='ГБ', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный объем памяти')),
                ('max_memory_type', models.CharField(blank=True, choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=20, verbose_name='Тип максимальной памяти')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель материнской платы',
                'verbose_name_plural': 'Модели материнских плат',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
                ('motherboard_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboards', to='components.motherboardmodel', verbose_name='Модель материнской платы')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.CreateModel(
            name='RAMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Уникален в рамках производителя', max_length=100, verbose_name='Парт-номер')),
                ('memory_type', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=20, verbose_name='Тип памяти')),
                ('memory_size_gb', models.PositiveIntegerField(help_text='ГБ', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Объем памяти')),
                ('base_frequency_mhz', models.PositiveIntegerField(help_text='МГц', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Базовая частота')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='devices.vendor', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель RAM',
                'verbose_name_plural': 'Модели RAM',
                'ordering': ['vendor', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_components', to='devices.device', verbose_name='Устройство')),
                ('ram_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rams', to='components.rammodel', verbose_name='Модель RAM')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM',
            },
        ),
        migrations.AddConstraint(
            model_name='cpumodel',
            constraint=models.CheckConstraint(condition=models.Q(('cores__gte', 1), ('threads__gte', 1)), name='cpu_model_cores_threads_positive'),
        ),
        migrations.AddConstraint(
            model_name='cpumodel',
            constraint=models.CheckConstraint(condition=models.Q(('threads__gte', models.F('cores'))), name='cpu_model_threads_gte_cores'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('size_gb__gte', 1)), name='disk_model_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='diskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('rpm', None), ('rpm__gte', 1), _connector='OR'), name='disk_model_rpm_null_or_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='motherboardmodel',
            constraint=models.CheckConstraint(condition=models.Q(('max_memory_gb__gte', 1)), name='motherboard_model_max_memory_positive'),
        ),
        migrations.AddConstraint(
            model_name='rammodel',
            constraint=models.CheckConstraint(condition=models.Q(('memory_size_gb__gte', 1), ('base_frequency_mhz__gte', 1)), name='ram_model_size_frequency_positive'),
        ),
    ]
