# Generated by Django 6.1 on 2026-08-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('devices', '0008_operatingsystem_device_operating_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disks', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
